title: Deck X • Sample Scene (Unity)
description: Documentação essencial para configuração, estudo e uso da cena de amostra.
theme: just-the-docs
url: https://github.com/Stremps

# busca e navegação
search_enabled: true
just_the_docs:
  navigation_depth: 2

# links de topo
aux_links:
  "Repositório no GitHub":
    - "https://github.com/Stremps"

# quando for trabalhar com esquema escuro próprio depois:
# color_scheme: deckx
